services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_db
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/abcd1234
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    ports:
      - "7474:7474"
      - "7687:7687"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    container_name: rag_api
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j_db:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=abcd1234
      - QDRANT_URL=http://qdrant_db:6333
      - QDRANT_API_KEY=""
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
      - OPENAI_DEPLOYMENT_EMBEDDING=${OPENAI_DEPLOYMENT_EMBEDDING}
      - INDEX_NAME=${INDEX_NAME}
    depends_on:
      neo4j:
        condition: service_healthy
      qdrant:
        condition: service_started
    restart: unless-stopped

  frontend:
    build:
      context: src/frontend
      dockerfile: Dockerfile
    container_name: rag_frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - api
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
