services:
  neo4j:
    image: neo4j:latest
    volumes:
      - /$HOME/Documents/neo4j/logs:/logs
      - /$HOME/Documents/neo4j/config:/config
      - /$HOME/Documents/neo4j/data:/data
      - /$HOME/Documents/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/abcd1234
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage
